### ISSUE TITLE
Launch Agent does not work

### ISSUE THREAD

**Issue by fridtjof** [pmkary/starlight#1]
When trying to start starlight with `launchctl start us.kary.starlight`, it exits with exit code 3.

However, when launching it by hand, in a Terminal, it works fine. Do note that on the first time, a security warning pops up asking for access to "System Events.app" by Terminal.app.

**Comment by pouyakary** [comment]
@fridtjof thanks for informing me! I have added a first force-run in the makefile to make it happen.!
